### ISSUE TITLE
地理位置及地图

### ISSUE THREAD

**Issue by wxy** [bestony/WeApp-Password#66]
1、（模拟器中）地理位置获取似乎只能到市级，即定位到市中心。
2、显示地图上方，如果没有备注，不要显示“没有填写描述”。
3、地图应该有一个 marker 来标示选定位置，并可以在编辑状态由用户移动。
4、编辑场景时，“更新地址”应该变成地图选点，考虑有三：1、点击该按钮有可能误操作；2、并不知道实际处于什么地点，精确度不确定。
5、记录的地理信息中，应该包括三个数据，经度、维度和缩放比例尺。

**Comment by bestony** [comment]
真机测试可以获取到精确位置。
2 已经fix 
3 已经提供了显示。
5 比例尺信息无法获取。
