### ISSUE TITLE
场景详情的一些小问题

### ISSUE THREAD

**Issue by wxy** [bestony/WeApp-Password#67]
1、时间进度条使用绿色吧，这个橙色不太好看。
2、如未添加场景描述，则不必显示“没有添加描述”，如有，则应该显示在地铁框之外的上方。
3、编辑场景时，不能自动选择该场景之前设定的场景分类。
4、编辑场景时，账户、场景名、类型和备注等字段名的字体样式应该和字段值有区分：
     - 字段值字体要小一些
     - 字段值颜色要灰色
     - 字段值要有输入的感觉，比如说像个框，或者有下划线
     - 场景类型可以用下拉菜单，以给位置地图留下空间
5、第一次保存可以，你修改地图之后，再次编辑，（没有点击更新地址）我再保存就报错：“数据存储出错”
6、没有显示场景距离的地方了。

**Comment by bestony** [comment]
由于整体坐标系转换，不确定对距离的影响有多大，暂时放弃这个特性。
