### ISSUE TITLE
过个年，咋很多ios机子上的场景都没了。。。

### ISSUE THREAD

**Issue by ximply** [bestony/WeApp-Password#76]

**Comment by ximply** [comment]
目前发现以下会出现丢失情况：
iphone6S   IOS 10.3.3
iphone6P  IOS 11.3beta
iphone7    IOS 11.2.3/11.2.6
iphone8P  IOS 11.2.5
iphone8    IOS 11.2.6

**Comment by bestony** [comment]
目前怀疑是  iOS 自动的垃圾清理机制。我研究研究有没有 workaround 来解决

**Comment by wxy** [comment]
必须得将保存备份机制解决了。

**Comment by ximply** [comment]
额。。。 连安卓机都开始出现场景丢失了

**Comment by ximply** [comment]
还有个问题：扫描添加了场景 然后不显示 以为没加进去  再次扫描却提示已经添加该场景。。。

**Comment by Vic020** [comment]
小程序有必须有外源存储，ios的小程序内核升级会清理，android的清理工具也会删除。

**Comment by wxy** [comment]
目前发现该小程序的备份和恢复存在问题。此外，也缺乏自动备份机制。

**Comment by daiaji** [comment]
那这不是比google自家的身份验证更惨？
还是放弃部署好了（反正也不喜欢微信）

**Comment by ximply** [comment]
最终还是选择了app，不过还是很感谢这个小程序
